//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GazeToSpeech.Common {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GazeToSpeech.Common.TextResources", typeof(TextResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string LblBack {
            get {
                return ResourceManager.GetString("LblBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration complete.
        /// </summary>
        internal static string LblCalibrationComplete {
            get {
                return ResourceManager.GetString("LblCalibrationComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System will calibrate your eyes. Look straight ahead for 5 seconds..
        /// </summary>
        internal static string LblCalibrationInit {
            get {
                return ResourceManager.GetString("LblCalibrationInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera facing.
        /// </summary>
        internal static string LblFacing {
            get {
                return ResourceManager.GetString("LblFacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        internal static string LblFront {
            get {
                return ResourceManager.GetString("LblFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LblLanguage {
            get {
                return ResourceManager.GetString("LblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing facial detection library. This might take a while.
        /// </summary>
        internal static string LblLoadingSlow {
            get {
                return ResourceManager.GetString("LblLoadingSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocal Eyes.
        /// </summary>
        internal static string TtlApp {
            get {
                return ResourceManager.GetString("TtlApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture eyes.
        /// </summary>
        internal static string TtlCapture {
            get {
                return ResourceManager.GetString("TtlCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string TtlHome {
            get {
                return ResourceManager.GetString("TtlHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TtlSettings {
            get {
                return ResourceManager.GetString("TtlSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Becker Communication System.
        /// </summary>
        internal static string TtlSubtitle {
            get {
                return ResourceManager.GetString("TtlSubtitle", resourceCulture);
            }
        }
    }
}
